# Ansible inventory generated by Terraform
# File: hosts.ini

[controllers]
%{ for name, node in controllers ~}
${node.hostname} ansible_host=${node.static_ip} ansible_user=ubuntu node_role=controller mac_address=${node.mac_address}
%{ endfor ~}

[workers]
%{ for name, node in workers ~}
${node.hostname} ansible_host=${node.static_ip} ansible_user=ubuntu node_role=worker mac_address=${node.mac_address}
%{ endfor ~}

[cluster:children]
controllers
workers

[cluster:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3